The dataset (https://www.kaggle.com/andrewmvd/fetal-health-classification) contains 2,126 records of features extracted from Cardiotocogram exams,
which were then classified by three expert obstetricians into three classes:
1) Normal
2) Suspect
3) Pathological

Here is a multiclass classification model that classifies fetal health states (i.e., normal, suspect, and pathological)
based on all Cardiotocogram features available in the dataset

In [114]:
# show all ouputs in a cell
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = 'all'

In [115]:
# mount the google drive to colab
from google.colab import drive
drive.mount("/drive")

Drive already mounted at /drive; to attempt to forcibly remount, call drive.mount("/drive", force_remount=True).


In [116]:
# Read the data into Google Colab using .read_csv() function.
# import numpy and pandas
import numpy as np
import pandas as pd
df = pd.read_csv('/drive/MyDrive/fetal_health.csv')
df

baseline value  accelerations  fetal_movement  uterine_contractions  \
0              120.0          0.000           0.000                 0.000   
1              132.0          0.006           0.000                 0.006   
2              133.0          0.003           0.000                 0.008   
3              134.0          0.003           0.000                 0.008   
4              132.0          0.007           0.000                 0.008   
...              ...            ...             ...                   ...   
2121           140.0          0.000           0.000                 0.007   
2122           140.0          0.001           0.000                 0.007   
2123           140.0          0.001           0.000                 0.007   
2124           140.0          0.001           0.000                 0.006   
2125           142.0          0.002           0.002                 0.008   

      light_decelerations  severe_decelerations  prolongued_decelerations  \
0                   0.000                   0.0                       0.0   
1                   0.003                   0.0                       0.0   
2                   0.003                   0.0                       0.0   
3                   0.003                   0.0                       0.0   
4                   0.000                   0.0                       0.0   
...                   ...                   ...                       ...   
2121                0.000                   0.0                       0.0   
2122                0.000                   0.0                       0.0   
2123                0.000                   0.0                       0.0   
2124                0.000                   0.0                       0.0   
2125                0.000                   0.0                       0.0   

      abnormal_short_term_variability  mean_value_of_short_term_variability  \
0                                73.0                                   0.5   
1                                17.0                                   2.1   
2                                16.0                                   2.1   
3                                16.0                                   2.4   
4                                16.0                                   2.4   
...                               ...                                   ...   
2121                             79.0                                   0.2   
2122                             78.0                                   0.4   
2123                             79.0                                   0.4   
2124                             78.0                                   0.4   
2125                             74.0                                   0.4   

      percentage_of_time_with_abnormal_long_term_variability  ...  \
0                                                  43.0       ...   
1                                                   0.0       ...   
2                                                   0.0       ...   
3                                                   0.0       ...   
4                                                   0.0       ...   
...                                                 ...       ...   
2121                                               25.0       ...   
2122                                               22.0       ...   
2123                                               20.0       ...   
2124                                               27.0       ...   
2125                                               36.0       ...   

      histogram_min  histogram_max  histogram_number_of_peaks  \
0              62.0          126.0                        2.0   
1              68.0          198.0                        6.0   
2              68.0          198.0                        5.0   
3              53.0          170.0                       11.0   
4              53.0          170.0                   

In [117]:
# Use .info() to get a short description of the dataframe.
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2126 entries, 0 to 2125
Data columns (total 22 columns):
 #   Column                                                  Non-Null Count  Dtype  
---  ------                                                  --------------  -----  
 0   baseline value                                          2126 non-null   float64
 1   accelerations                                           2126 non-null   float64
 2   fetal_movement                                          2126 non-null   float64
 3   uterine_contractions                                    2126 non-null   float64
 4   light_decelerations                                     2126 non-null   float64
 5   severe_decelerations                                    2126 non-null   float64
 6   prolongued_decelerations                                2126 non-null   float64
 7   abnormal_short_term_variability                         2126 non-null   float64
 8   mean_value_of_short_term_variability  

In [118]:
# Investigate the target (fetal_health) to assess the prevalence of each fetal health status in the dataframe?
print('1.0 = Normal, 2.0 = Suspect, 3.0 = Pathological')
print()
df['fetal_health'].value_counts()

1.0 = Normal, 2.0 = Suspect, 3.0 = Pathological



fetal_health
1.0    1655
2.0     295
3.0     176
Name: count, dtype: int64

In [119]:
# Create a pipeline to process numeric features.

from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.impute import SimpleImputer

pipeline = Pipeline([
    # replace missing values of a feature with its median
    ('replace_missing_values', SimpleImputer(strategy='median')),
    # standardize the feature
    ('scaler', StandardScaler())
    ])

In [120]:
# Train/split the dataframe with the test set occupying 20% of the data.

from sklearn.model_selection import train_test_split

# separate the target from the features
y = np.c_[df['fetal_health']]
X = df.drop('fetal_health', axis=1)

# apply train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [121]:
# Fit and transform the train set using the pipeline.

pipeline.fit_transform(X_train)

array([[-0.34564246,  1.50653066,  0.50114149, ...,  0.12286096,
        -0.1177312 , -0.52730614],
       [-0.34564246,  1.50653066, -0.13227155, ..., -0.01459454,
        -0.54546342, -0.52730614],
       [-1.04622928, -0.29253756, -0.20535767, ..., -0.70187204,
        -0.61675213, -0.52730614],
       ...,
       [ 0.65519586, -0.80655706, -0.20535767, ...,  0.26031646,
        -0.61675213,  1.11148808],
       [-1.04622928, -0.80655706, -0.20535767, ..., -0.90805529,
        -0.15337555,  1.11148808],
       [-0.84606162, -0.80655706, -0.20535767, ..., -0.83932754,
         0.38128973,  1.11148808]])

In [122]:
# Transform the test set using the pipeline.

pipeline.transform(X_test)

array([[-0.04539096, -0.80655706, -0.20535767, ...,  0.12286096,
        -0.36724166,  1.11148808],
       [ 1.85620185, -0.80655706, -0.20535767, ...,  1.49741596,
        -0.61675213,  1.11148808],
       [ 1.15561502,  2.7915794 ,  0.42805537, ...,  1.84105471,
        -0.26030861,  1.11148808],
       ...,
       [ 1.35578269,  1.24952092,  0.01390069, ...,  1.42868821,
        -0.29595296, -0.52730614],
       [ 0.25486053, -0.29253756, -0.20535767, ...,  0.12286096,
        -0.58110778, -0.52730614],
       [ 1.55595035, -0.29253756, -0.20535767, ...,  1.70359921,
        -0.40288602,  1.11148808]])

In [123]:
# Fit a stochastic gradient descent (SGD) classifier on the train set.
from sklearn.linear_model import SGDClassifier

# invoke SGD
SGD = SGDClassifier()
# fit on the train set
SGD.fit(X_train, y_train)
y_pred = SGD.predict(X_test)

/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SGDClassifier()

In [124]:
# Calculate precision, recall, and F-1 score based on the predictions made by the SGD classifier on the test set.
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score
from sklearn.metrics import accuracy_score

print('Accuracy: '+str(accuracy_score(y_test, y_pred)))
print('Precision: '+str(precision_score(y_test, y_pred, average = 'macro')))
print('Recall: '+str(recall_score(y_test, y_pred, average = 'macro')))
print('F1: '+str(f1_score(y_test, y_pred, average = 'macro')))

Accuracy: 0.8497652582159625
Precision: 0.6566221089213539
Recall: 0.6291620876472516
F1: 0.59102679693993


In [125]:
# Compare the accuracy of the SGD classifier with the accuracy of the dummy classifier (“raw” accuracy).
# Compare the baseline accuracy to the model accuracy reported in 13. Does your model perform better than the baseline?
from sklearn.dummy import DummyClassifier

# invoke dummy classifier
dummy = DummyClassifier(strategy='most_frequent')
# fit the train data
dummy.fit(X_train, y_train)
# predict using the train features
dummy.predict(X_train)
print()
# get the accuracy of the dummy classifier
dummy.score(X_train, y_train)

DummyClassifier(strategy='most_frequent')

array([1., 1., 1., ..., 1., 1., 1.])

0.7741176470588236

Dummy is worse than SGD - that's good!

In [58]:
# Train a random-forest classifier and compare modeling results (i.e., accuracy, precision, recall, and F-1 score on the test set)
# with those obtained with the SGD classifier.

from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

RndmForest = RandomForestClassifier()
RndmForest.fit(X_train, y_train)
y_pred_RndmForest = RndmForest.predict(X_test)

print('Accuracy: '+str(accuracy_score(y_test, y_pred_RndmForest)))
print('Precision: '+str(precision_score(y_test, y_pred_RndmForest, average = 'macro')))
print('Recall: '+str(recall_score(y_test, y_pred_RndmForest, average = 'macro')))
print('F1: '+str(f1_score(y_test, y_pred_RndmForest, average = 'macro')))

<ipython-input-58-796879b28aca>:6: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  RndmForest.fit(X_train, y_train)


RandomForestClassifier()

Accuracy: 0.9342723004694836
Precision: 0.9043687604912094
Recall: 0.8461082415619009
F1: 0.8728573358629776

RandomForest is much better!


RandomForest is much better!